### ISSUE TITLE
Virginia has a county column instead of county_name

### ISSUE THREAD

**Issue by chriszs** [PublicI/us-polling-places#44]
And it's blank.

**Comment by pratheekrebala** [comment]
Thanks! The county column is blank for the 2012 and 2014 because the data came from VIP.

Almost all the VIP datasets will be missing the county_name column because the underlying data did not come with it. I am testing the geocodes to see if we can impute county but it's iffy. I'll open a separate issue to discuss that.

**Comment by chriszs** [comment]
Makes sense. I'm a little confused about when we leave a column out versus leaving it blank, but comparatively doesn't seem that important. Could probably close this issue.
